package lawsuitsapp.lawsuits.model;

import lombok.Data;
import lombok.NoArgsConstructor;

import java.sql.Timestamp;
import java.time.LocalDateTime;


@Data
@NoArgsConstructor
public class Document {

    int ID;

    String name;
    int archiveNumber;
    int caseNumber;
    boolean isInput=false;            // true - vlezen
    Timestamp createdAt;                // autogenerated koga se pravi document
    LocalDateTime documentDate;      // go vnesuva pravnikot

    // connections
    Court court;
    Employee createdBy;
    Case caseId;


}
