package lawsuitsapp.lawsuits.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import javax.persistence.Entity;
import javax.validation.constraints.NotBlank;
import java.sql.Timestamp;
import java.time.LocalDate;
import java.time.LocalDateTime;

@Entity
@Data
@NoArgsConstructor
@Table(name = "documents")
public class Document {

    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    int ID;

    String name;
    int archiveNumber;

    boolean isInput=false;            // true - vlezen
    Timestamp createdAt;                // autogenerated koga se pravi document
    LocalDate documentDate;      // go vnesuva pravnikot

    String fileType;
    byte[] data;

    // connections

    @JsonIgnore
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "courtId")
    Court court;

    @JsonIgnore
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "employeeId")
    Employee createdBy;


    //@NotBlank
    //int caseNumber;
    //Case caseId;



    public Document(String name, int archiveNumber, boolean isInput,
                    LocalDate documentDate, String fileType, byte[] data, Employee employee, Court court){

        createdAt = new Timestamp(System.currentTimeMillis());
        this.name = name;
        this.archiveNumber = archiveNumber;
        this.isInput = isInput;
        this.documentDate = documentDate;
        this.fileType = fileType;
        this.data = data;
        this.createdBy = employee;
        this.court = court;
    }

}
